name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Save SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to web1
        run: |
          scp -i key.pem -r ./dist ubuntu@${{ secrets.EC2_1_PUBLIC_IP }}:/home/ubuntu/my-app/dist
          ssh -i key.pem ubuntu@${{ secrets.EC2_1_PUBLIC_IP }} "sudo systemctl restart nginx"

      - name: Deploy to web2
        run: |
          scp -i key.pem -r ./dist ubuntu@${{ secrets.EC2_2_PUBLIC_IP }}:/home/ubuntu/my-app/dist
          ssh -i key.pem ubuntu@${{ secrets.EC2_2_PUBLIC_IP }} "sudo systemctl restart nginx"
